on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Bats
        run: npm install -g bats

      - name: bats version
        run: bats -v
